trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2 # Ejemplo de una tarea para usar .NET SDK
  inputs:
    version: '6.x'
    includePreviewVersions: true
  displayName: 'Install .NET SDK'

- script: |
    dotnet build --configuration Release
    dotnet test --configuration Release
  displayName: 'Build and Test'

- task: PublishBuildArtifacts@1 # Publica los artefactos de la compilación
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'